name: Test_Workflow
on:
  push:
    branches:
      - '*'
  schedule:
    - cron: '00 12 1 * *'

jobs:
  getSha:
    runs-on: ubuntu-latest
    steps:
      - run: |
          response=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/commits/d79d2bd9")
          hash=$(echo "$response" | jq -r '.sha')
          echo "LONG_HASH=$hash" >> $GITHUB_OUTPUT

#      - name: put to hash
#        run: echo "LONG_HASH=${{ steps.get_hash.outputs.long_hash }}" >> $GITHUB_ENV
  checkout:
    needs: getSha
    runs-on: ubuntu-latest
    env:
      longsha=${{ needs.step1.outputs.LONG_HASH }}"
    steps:
      - name: Print Hash
        run: echo $longsha
      - name: Get commit SHA
        run: echo ${{ github.sha }}
      - name: printhello
        uses: actions/checkout@v4
        with:
          ref: ${{ env.longsha }}
          path: sourcecode

      - name: printpath
        run: echo `pwd`
      - name: listfiles
        run: echo `ls -ll`