name: Test_Workflow
on:
  push:
    branches:
      - '*'
  schedule:
    - cron: '*/10 * * * *'

jobs:
  echo_hello:
    runs-on: ubuntu-latest
    steps:
      - name: printhello
        uses: actions/checkout@v4
