name: Test_Workflow
on:
  push:
    branches:
      - '*'
  schedule:
    - cron: '00 12 1 * *'

jobs:
  echo_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Get Commit Information
        id: commit_info
        run: |
          response=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/commits/d79d2bd9")
          hash=$(echo "$response" | jq -r '.sha')
          echo "::set-output name=hash::$hash"
      - name: put to hash
        run: echo "LONG_HASH=${{ steps.get_hash.outputs.long_hash }}" >> $GITHUB_ENV
      - name: Print Hash
        run: echo $LONG_HASH

      - name: Get commit SHA
        run: echo ${{ github.sha }}
      - name: printhello
        uses: actions/checkout@v4
        with:
          ref: $LONG_HASH
          path: sourcecode

      - name: printpath
        run: echo `pwd`
      - name: listfiles
        run: echo `ls -ll`