name: Test_Workflow
on:
  push:
    branches:
      - '*'
  schedule:
    - cron: '00 12 1 * *'

jobs:
  echo_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Get commit SHA
        run: echo ${{ github.sha }}
      - name: printhello
        uses: actions/checkout@v1

      - name: longhash
        run: echo "::set-output name=long_hash::$(git rev-parse 3eded484)"
      - name: printpath
        run: echo `pwd`
      - name: checkoutagain
        uses: actions/checkout@v4
        with:
          ref: d25761cb2f848389fbeb040258e0d10bc87f8b06
          path: sourcecode
      - name: listfiles
        run: echo `ls -ll`