name: Test_Workflow
on:
  push:
    branches:
      - '*'
  schedule:
    - cron: '00 12 1 * *'

jobs:
  echo_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Get commit SHA
        run: echo ${{ github.sha }}
      - name: printhello
        uses: actions/checkout@v4
        with:
          ref: '99588506'