name: Test_Workflow
on:
  push:
    branches:
      - '*'
  schedule:
    - cron: '00 12 1 * *'

jobs:
  getSha:
    runs-on: ubuntu-latest
    outputs:
      longsha: ${{ steps.getlongsha.outputs.LONG_HASH }}
    steps:
      - id: getlongsha
        run: |
          response=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/commits/d79d2bd9")
          hash=$(echo "$response" | jq -r '.sha')
          echo $hash
          echo "LONG_HASH=5cdb5495b47d89306a7cd7a0c77710f324208f79" >> "$GITHUB_OUTPUT"

#      - name: put to hash
#        run: echo "LONG_HASH=${{ steps.get_hash.outputs.long_hash }}" >> $GITHUB_ENV
  checkout:
    needs: getSha
    runs-on: ubuntu-latest
#    env:
#      longsha=${{ needs.step1.outputs.LONG_HASH }}
    steps:
      - name: Print Hash
        run: |
          echo "${{ needs.step1.outputs }}"
          echo "longsha=${{ needs.getSha.outputs.longsha }}"
          echo "$longsha"
      - name: Get commit SHA
        run: |
          echo ${{ needs.getSha.outputs.longsha }}

      - name: printhello
        uses: actions/checkout@v3
        with:
          ref:  ${{ needs.getSha.outputs.longsha }}

      - name: printpath
        run: echo `pwd`
      - name: listfiles
        run: echo `ls -ll`