name: Deploy
on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Test_Workflow
    types:
      - Complete

jobs:
  downloadWorkflowArtifact:
    runs-on: ubuntu-latest
    steps:
      - name: print123
        shell: bash
        run: echo 'hello'