name: Deploy
on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Test_Workflow
    types:
      - completed

jobs:
  downloadWorkflowArtifact:
    runs-on: ubuntu-latest
    steps:
      - name: print123
        shell: bash
        run: echo ${{github.event.workflow_run.head_sha}}
      - name: printurl
        shell: bash
        run: echo ${{github.event.workflow_run.artifacts_url}}