name: Schedule_Workflow
on:
  push:
    paths:
      - .github/workflows/Schedule.yaml
  schedule:
    - cron: '*/15 * * * *'

jobs:
  getSha:
    runs-on: ubuntu-latest
    steps:
      - name: sayHello
        run: echo 'hello'